version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=data
      - POSTGRES_USER=spring
      - POSTGRES_DB=book
